### ISSUE TITLE
Save state and restore after resizing?

### ISSUE THREAD

**Issue by Prestaul** [shannonmoeller/get-context#2]
I wonder if there is a way to save the canvas state (i.e. line width, stroke style, fill style, line caps, line joins, composite method, transform matrix, etc...) and restore after resizing. If there is nothing more elegant than a manual method then it may not be worth it...

Concerns this method: https://github.com/shannonmoeller/get-context/blob/master/lib/GetContext.js#L68-L78

**Comment by shannonmoeller** [comment]
I don't think there's a good way to handle this correctly for every use case. Too many unknowns and some people may rely on the resize to clear out the current state.
